---
- name: Range Event Rulebook
  hosts: localhost
  sources:
    - name: range
      ansible.eda.range:
        limit: 30
  rules:
    - name: Print message when index is 27
      condition: event.i == 27
      action:
        debug:
          msg: "I am learning to write a rulebook as a part of training"


