---
- name: Range Event Rulebook
  hosts: localhost
  sources:
    - ansible.eda.range:
        limit: 30

  rules:
    - name: Print message when index is 27
      condition: event.payload.index == 27
      action:
        debug:
          msg: "I am learning to write a rulebook as a part of training"

